#!/bin/bash
# =========================================================
# DairyBox – Docker Entrypoint
# Waits for MySQL, runs schema, then starts Apache
# =========================================================
set -e

echo "========================================"
echo " DairyBox – Starting up..."
echo "========================================"

# Environment variable defaults
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-dairybox_db}"
DB_USER="${DB_USER:-root}"
DB_PASS="${DB_PASS:-}"

# Write config/database.php from environment variables
cat > /var/www/html/config/database.php << EOF
<?php
// Auto-generated by docker-entrypoint.sh
define('DB_HOST', '${DB_HOST}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
define('DB_NAME', '${DB_NAME}');
define('DB_PORT', '${DB_PORT}');

function getDB(): PDO {
    static \$pdo = null;
    if (\$pdo === null) {
        try {
            \$dsn = "mysql:host=" . DB_HOST . ";port=" . DB_PORT . ";dbname=" . DB_NAME . ";charset=utf8mb4";
            \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ]);
        } catch (PDOException \$e) {
            die('Database error: ' . htmlspecialchars(\$e->getMessage()));
        }
    }
    return \$pdo;
}
EOF

echo "[✓] config/database.php written"

# Wait for MySQL to be ready
echo "[ ] Waiting for MySQL at ${DB_HOST}:${DB_PORT}..."
MAX_TRIES=30
COUNT=0
until mysql -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASS}" -e "SELECT 1" > /dev/null 2>&1; do
    COUNT=$((COUNT+1))
    if [ $COUNT -ge $MAX_TRIES ]; then
        echo "[✗] MySQL not reachable after ${MAX_TRIES} attempts. Exiting."
        exit 1
    fi
    echo "    Attempt $COUNT/$MAX_TRIES – retrying in 3s..."
    sleep 3
done
echo "[✓] MySQL is ready!"

# Create database if it doesn't exist
mysql -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASS}" \
    -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "[✓] Database '${DB_NAME}' ensured"

# Check if tables already exist (idempotent)
TABLE_COUNT=$(mysql -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASS}" \
    -D"${DB_NAME}" -e "SHOW TABLES;" 2>/dev/null | wc -l)

if [ "$TABLE_COUNT" -lt "5" ]; then
    echo "[ ] Running database schema..."
    mysql -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASS}" \
        "${DB_NAME}" < /var/www/html/database/dairybox_db.sql
    echo "[✓] Schema and seed data loaded!"
else
    echo "[✓] Database already initialized ($TABLE_COUNT tables found), skipping."
fi

echo "========================================"
echo " DairyBox is ready! Starting Apache..."
echo "========================================"

# Start Apache in foreground
exec apache2-foreground
