#!/bin/bash
# =========================================================
# DairyBox – Docker Entrypoint
# =========================================================
set -e

echo "========================================"
echo " DairyBox – Starting up..."
echo "========================================"

# Use environment variables if set, otherwise keep existing config/database.php
if [ -n "$DB_HOST" ]; then
    echo "[ ] Writing config/database.php from environment variables..."

    cat > /var/www/html/config/database.php << EOF
<?php
// Auto-generated by docker-entrypoint.sh from environment variables
define('DB_HOST', '${DB_HOST}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
define('DB_NAME', '${DB_NAME:-railway}');
define('DB_PORT', '${DB_PORT:-3306}');

function getDB(): PDO {
    static \$pdo = null;
    if (\$pdo === null) {
        try {
            \$dsn = "mysql:host=" . DB_HOST . ";port=" . DB_PORT . ";dbname=" . DB_NAME . ";charset=utf8mb4";
            \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ]);
        } catch (PDOException \$e) {
            die('Database error: ' . htmlspecialchars(\$e->getMessage()));
        }
    }
    return \$pdo;
}
EOF
    echo "[✓] config/database.php written from environment variables"
    FINAL_HOST="${DB_HOST}"
    FINAL_PORT="${DB_PORT:-3306}"
    FINAL_USER="${DB_USER}"
    FINAL_PASS="${DB_PASS}"
    FINAL_DB="${DB_NAME:-railway}"
else
    echo "[✓] No environment variables found – using existing config/database.php"
    # Read values from existing config/database.php
    FINAL_HOST=$(php -r "require '/var/www/html/config/database.php'; echo DB_HOST;")
    FINAL_PORT=$(php -r "require '/var/www/html/config/database.php'; echo DB_PORT;")
    FINAL_USER=$(php -r "require '/var/www/html/config/database.php'; echo DB_USER;")
    FINAL_PASS=$(php -r "require '/var/www/html/config/database.php'; echo DB_PASS;")
    FINAL_DB=$(php -r "require '/var/www/html/config/database.php'; echo DB_NAME;")
fi

echo "[ ] Connecting to MySQL at ${FINAL_HOST}:${FINAL_PORT}..."

# Wait for MySQL to be reachable
MAX_TRIES=20
COUNT=0
until mysql -h"${FINAL_HOST}" -P"${FINAL_PORT}" -u"${FINAL_USER}" -p"${FINAL_PASS}" \
    --connect-timeout=5 -e "SELECT 1;" > /dev/null 2>&1; do
    COUNT=$((COUNT+1))
    if [ $COUNT -ge $MAX_TRIES ]; then
        echo "[✗] MySQL not reachable after ${MAX_TRIES} attempts."
        echo "    Host: ${FINAL_HOST}:${FINAL_PORT}"
        echo "    Check your DB credentials and network settings."
        echo "[ ] Starting Apache anyway (app may show DB errors until DB is reachable)..."
        exec apache2-foreground
    fi
    echo "    Attempt $COUNT/$MAX_TRIES – retrying in 3s..."
    sleep 3
done

echo "[✓] MySQL connected successfully!"

# Check if tables already exist
TABLE_COUNT=$(mysql -h"${FINAL_HOST}" -P"${FINAL_PORT}" -u"${FINAL_USER}" -p"${FINAL_PASS}" \
    -D"${FINAL_DB}" -e "SHOW TABLES;" 2>/dev/null | wc -l)

if [ "$TABLE_COUNT" -lt "5" ]; then
    echo "[ ] Running database schema and seed data..."
    mysql -h"${FINAL_HOST}" -P"${FINAL_PORT}" -u"${FINAL_USER}" -p"${FINAL_PASS}" \
        "${FINAL_DB}" < /var/www/html/database/dairybox_db.sql
    echo "[✓] Schema and seed data loaded!"
else
    echo "[✓] Database already has ${TABLE_COUNT} tables – skipping import."
fi

echo "========================================"
echo " DairyBox is ready! Starting Apache..."
echo "========================================"

exec apache2-foreground
